# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test

on:
  push:
    branches: [ "dev1.0" ]
  pull_request:
    branches: [ "dev1.0" ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run standard
        run: npx standard
      - name: Run test
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          npm test
      - name: Run coverage
        id: coverage
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          val=$(npm run coverage | tail -5)
          echo "COVERAGE="${val//:/*}"" >> $GITHUB_OUTPUT
      - name: Show coverage
        run: echo "The selected color is ${{ steps.coverage.outputs.COVERAGE }}"
      - name: Statements Coverage
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 9551338162f925dc43214b3fe9ecaf13
          filename: codejavu_coverage_statements.json
          label: statements coverage
          message: ${{ matrix.node-version }}
          color: orange
      - name: Functions Coverage
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 11be7f5d7651527ffcf24cc24a8466b2
          filename: codejavu_coverage_functions.json
          label: functions coverage
          message: ${{ matrix.node-version }}
          color: orange
      - name: Lines Coverage
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: c35ad03761983d3d939a62a2f1d6db70
          filename: codejavu_coverage_lines.json
          label: lines coverage
          message: ${{ matrix.node-version }}
          color: orange
      - name: Branches Coverage
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6c5c47e3ca816021a6ce013b04dd3880
          filename: codejavu_coverage_branches.json
          label: branches coverage
          message: ${{ matrix.node-version }}
          color: orange

